version: '2'
services:

##### ################### #####
##### Services Instances  #####
##### ################### #####
  batman-service:
    build: ./movies-service
    volumes:
      - "/Users/sfbs/.m2:/root/.m2"
    ports:
      - "8082:8080"
    links:
      - dev-consul
    environment:
      - MOVIE_NAME=batman

  star-service:
    build: ./movies-service
    volumes:
      - "/Users/sfbs/.m2:/root/.m2"
    ports:
      - "8081:8080"
    links:
      - dev-consul
    environment:
      - MOVIE_NAME=star

  rating-service:
    build: ./rating-service
    environment:
    - NEO4J_HOSTNAME=neo4j
    - JWT_SECRET=123
    ports:
    - 3000:3000    

##### ################### #####
#####    API Gateway      #####
##### ################### #####
  api:
    build: ./api-gateway
    volumes:
      - "/Users/sfbs/.m2:/root/.m2"
    ports:
      - "8000:8080"
    links:
      - dev-consul

##### ############################## #####
##### Monitoring & Service Discovery #####
##### ############################## #####
  zipkin-server:
    build: ./tracer-dashboard
    volumes:
      - "/Users/sfbs/.m2:/root/.m2"
    links:
      - dev-consul

  hystrix-dashboard:
    build: ./hystrix-dashboard
    volumes:
      - "/Users/sfbs/.m2:/root/.m2"
    links:
      - dev-consul

  dev-consul:
    image: consul
    ports:
      - "8500:8500"

##### ############################## #####
##### Datastores                     #####
##### ############################## #####
  neo4j:
    image: neo4j
    environment:
    - NEO4J_AUTH=none
    ports:
    - 7474:7474

  # test:
  #   image: uzyexe/curl
  #   command: -v -X PUT http://dev-consul:8500/v1/agent/service/register
  #   links:
  #     - dev-consul