version: '2'
services:

##### ################### #####
##### Services Instances  #####
##### ################### #####
  batman-service:
    build: ./movies-service
    volumes:
      - "/Users/sfbs/.m2:/root/.m2"
    links:
      - service-discovery
    environment:
      - MOVIE_NAME=batman

  star-service:
    build: ./movies-service
    volumes:
      - "/Users/sfbs/.m2:/root/.m2"
    links:
      - service-discovery
    environment:
      - MOVIE_NAME=star

  ratings-service:
    build: ./rating-service
    environment:
      - NEO4J_HOSTNAME=neo4j
      - JWT_SECRET=123
    links:
      - service-discovery

    
##### ################### #####
#####    API Gateway      #####
##### ################### #####
  api-gateway:
    build: ./api-gateway
    volumes:
      - "/Users/sfbs/.m2:/root/.m2"
    ports:
      - "8000:8080"
    links:
      - service-discovery

##### ############################## #####
##### Monitoring & Service Discovery #####
##### ############################## #####
  zipkin-server:
    build: ./zipkin-server
    volumes:
      - "/Users/sfbs/.m2:/root/.m2"
    links:
      - service-discovery
    ports:
      - "8502:9411"

  hystrix-dashboard:
    build: ./hystrix-dashboard
    volumes:
      - "/Users/sfbs/.m2:/root/.m2"
    links:
      - service-discovery
    ports:
      - "8501:8080"

  service-discovery:
    image: consul
    ports:
      - "8500:8500"

##### ############################## #####
##### Datastores                     #####
##### ############################## #####
  neo4j:
    image: neo4j
    environment:
    - NEO4J_AUTH=none
